title: ProgrammerHQ
description: Join me in my journey of 100DaysOfCode and learn the stuffs that I will learn.

url: http://anku255.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: anku255
   twitter: __anku__
   email: ankitt255@gmail.com
